### ISSUE TITLE
UI doesn't work

### ISSUE THREAD

**Issue by dimmonn** [cescoffier/vertx-microservices-examples#7]
when all services are started and once "invoke" is hit, nothing happens,
Circuit Breakers page and Services page is empty when a,b,c,d are started properly

Members [4] {
        Member [192.168.99.1]:5701
        Member [192.168.99.1]:5702
        Member [192.168.99.1]:5703 this
        Member [192.168.99.1]:5704
}

UI error

Failed to find a valid digest in the 'integrity' attribute for resource 'http://code.jquery.com/jquery-2.2.1.min.js' with computed SHA-256 integrity 'gvQgAFzTH6trSrAWoH1iPo9Xc96QxSZ3feW6kem+O00='. The resource has been blocked.
bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6
(anonymous) @ bootstrap.min.js:6
index.html:75 Uncaught ReferenceError: $ is not defined
    at index.html:75

**Comment by davidaparicio** [comment]
Hi @dimmonn 

Please update these files 

- aggregation-http/A/src/main/resources/assets/index.html
- aggregation-http/A/src/main/resources/assets/circuits.html
- aggregation-http/A/src/main/resources/assets/discovery.html

with

`integrity="sha384-8C+3bW/ArbXinsJduAjm9O7WNnuOcO+Bok/VScRYikawtvz4ZPrpXtGfKIewM9dK"`

It's due to a update of the JQuery 2.2.1 ;)
Is it working now? :)

References:
- https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
- https://www.srihash.org/

**Comment by dimmonn** [comment]
thanks, 

worked for me with 
integrity=""

**Comment by cescoffier** [comment]
Anyone fancy a PR?

**Comment by cescoffier** [comment]
Actually, I'm on it.
